Repository COSC481W-2024Winter/JARVIS, pull requests merged in 2024-04, with the labels that each got.

#65 Feature: Fetch weather based on current location
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/backend/weather_service.dart
  lib/home.dart
  pubspec.lock
  pubspec.yaml
  test/unit/weather_service_test.dart
Labels: enhancement

#70 Backend: Send profile data to GPT
  lib/backend/text_to_gpt_service.dart
  lib/profile_screen_jarvis.dart
  test/MOCK/profile_to_gpt_test.dart
Labels: enhancement, scope: backend, Sprint 3

#71 Fix weather UI for city names with two words
  lib/backend/weather_service.dart
  lib/home.dart
Labels: enhancement, scope: ui/ux, Sprint 3

#74 Update weather test
  test/unit/weather_service_test.dart
Labels: bug, test, Sprint 3

#82 remove: Removed the delete button
  lib/profile_screen_jarvis.dart
Labels: bug, scope: ui/ux

#85 Fix: GPT Text response
  lib/home.dart
Labels: bug, scope: ui/ux
